
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserWorldPin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model UserWorldPin
 * 
 */
export type UserWorldPinModel = runtime.Types.Result.DefaultSelection<Prisma.$UserWorldPinPayload>

export type AggregateUserWorldPin = {
  _count: UserWorldPinCountAggregateOutputType | null
  _avg: UserWorldPinAvgAggregateOutputType | null
  _sum: UserWorldPinSumAggregateOutputType | null
  _min: UserWorldPinMinAggregateOutputType | null
  _max: UserWorldPinMaxAggregateOutputType | null
}

export type UserWorldPinAvgAggregateOutputType = {
  rank: number | null
}

export type UserWorldPinSumAggregateOutputType = {
  rank: number | null
}

export type UserWorldPinMinAggregateOutputType = {
  createdAt: Date | null
  rank: number | null
  userId: string | null
  worldId: string | null
}

export type UserWorldPinMaxAggregateOutputType = {
  createdAt: Date | null
  rank: number | null
  userId: string | null
  worldId: string | null
}

export type UserWorldPinCountAggregateOutputType = {
  createdAt: number
  rank: number
  userId: number
  worldId: number
  _all: number
}


export type UserWorldPinAvgAggregateInputType = {
  rank?: true
}

export type UserWorldPinSumAggregateInputType = {
  rank?: true
}

export type UserWorldPinMinAggregateInputType = {
  createdAt?: true
  rank?: true
  userId?: true
  worldId?: true
}

export type UserWorldPinMaxAggregateInputType = {
  createdAt?: true
  rank?: true
  userId?: true
  worldId?: true
}

export type UserWorldPinCountAggregateInputType = {
  createdAt?: true
  rank?: true
  userId?: true
  worldId?: true
  _all?: true
}

export type UserWorldPinAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserWorldPin to aggregate.
   */
  where?: Prisma.UserWorldPinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserWorldPins to fetch.
   */
  orderBy?: Prisma.UserWorldPinOrderByWithRelationInput | Prisma.UserWorldPinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserWorldPinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserWorldPins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserWorldPins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserWorldPins
  **/
  _count?: true | UserWorldPinCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserWorldPinAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserWorldPinSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserWorldPinMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserWorldPinMaxAggregateInputType
}

export type GetUserWorldPinAggregateType<T extends UserWorldPinAggregateArgs> = {
      [P in keyof T & keyof AggregateUserWorldPin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserWorldPin[P]>
    : Prisma.GetScalarType<T[P], AggregateUserWorldPin[P]>
}




export type UserWorldPinGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserWorldPinWhereInput
  orderBy?: Prisma.UserWorldPinOrderByWithAggregationInput | Prisma.UserWorldPinOrderByWithAggregationInput[]
  by: Prisma.UserWorldPinScalarFieldEnum[] | Prisma.UserWorldPinScalarFieldEnum
  having?: Prisma.UserWorldPinScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserWorldPinCountAggregateInputType | true
  _avg?: UserWorldPinAvgAggregateInputType
  _sum?: UserWorldPinSumAggregateInputType
  _min?: UserWorldPinMinAggregateInputType
  _max?: UserWorldPinMaxAggregateInputType
}

export type UserWorldPinGroupByOutputType = {
  createdAt: Date
  rank: number
  userId: string
  worldId: string
  _count: UserWorldPinCountAggregateOutputType | null
  _avg: UserWorldPinAvgAggregateOutputType | null
  _sum: UserWorldPinSumAggregateOutputType | null
  _min: UserWorldPinMinAggregateOutputType | null
  _max: UserWorldPinMaxAggregateOutputType | null
}

export type GetUserWorldPinGroupByPayload<T extends UserWorldPinGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserWorldPinGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserWorldPinGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserWorldPinGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserWorldPinGroupByOutputType[P]>
      }
    >
  >



export type UserWorldPinWhereInput = {
  AND?: Prisma.UserWorldPinWhereInput | Prisma.UserWorldPinWhereInput[]
  OR?: Prisma.UserWorldPinWhereInput[]
  NOT?: Prisma.UserWorldPinWhereInput | Prisma.UserWorldPinWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"UserWorldPin"> | Date | string
  rank?: Prisma.IntFilter<"UserWorldPin"> | number
  userId?: Prisma.StringFilter<"UserWorldPin"> | string
  worldId?: Prisma.StringFilter<"UserWorldPin"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  world?: Prisma.XOR<Prisma.WorldScalarRelationFilter, Prisma.WorldWhereInput>
}

export type UserWorldPinOrderByWithRelationInput = {
  createdAt?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  world?: Prisma.WorldOrderByWithRelationInput
}

export type UserWorldPinWhereUniqueInput = Prisma.AtLeast<{
  userId_worldId?: Prisma.UserWorldPinUserIdWorldIdCompoundUniqueInput
  AND?: Prisma.UserWorldPinWhereInput | Prisma.UserWorldPinWhereInput[]
  OR?: Prisma.UserWorldPinWhereInput[]
  NOT?: Prisma.UserWorldPinWhereInput | Prisma.UserWorldPinWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"UserWorldPin"> | Date | string
  rank?: Prisma.IntFilter<"UserWorldPin"> | number
  userId?: Prisma.StringFilter<"UserWorldPin"> | string
  worldId?: Prisma.StringFilter<"UserWorldPin"> | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  world?: Prisma.XOR<Prisma.WorldScalarRelationFilter, Prisma.WorldWhereInput>
}, "userId_worldId">

export type UserWorldPinOrderByWithAggregationInput = {
  createdAt?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
  _count?: Prisma.UserWorldPinCountOrderByAggregateInput
  _avg?: Prisma.UserWorldPinAvgOrderByAggregateInput
  _max?: Prisma.UserWorldPinMaxOrderByAggregateInput
  _min?: Prisma.UserWorldPinMinOrderByAggregateInput
  _sum?: Prisma.UserWorldPinSumOrderByAggregateInput
}

export type UserWorldPinScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserWorldPinScalarWhereWithAggregatesInput | Prisma.UserWorldPinScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserWorldPinScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserWorldPinScalarWhereWithAggregatesInput | Prisma.UserWorldPinScalarWhereWithAggregatesInput[]
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserWorldPin"> | Date | string
  rank?: Prisma.IntWithAggregatesFilter<"UserWorldPin"> | number
  userId?: Prisma.StringWithAggregatesFilter<"UserWorldPin"> | string
  worldId?: Prisma.StringWithAggregatesFilter<"UserWorldPin"> | string
}

export type UserWorldPinCreateInput = {
  createdAt?: Date | string
  rank?: number
  user: Prisma.UserCreateNestedOneWithoutWorldPinsInput
  world: Prisma.WorldCreateNestedOneWithoutUserPinsInput
}

export type UserWorldPinUncheckedCreateInput = {
  createdAt?: Date | string
  rank?: number
  userId: string
  worldId: string
}

export type UserWorldPinUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutWorldPinsNestedInput
  world?: Prisma.WorldUpdateOneRequiredWithoutUserPinsNestedInput
}

export type UserWorldPinUncheckedUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  worldId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserWorldPinCreateManyInput = {
  createdAt?: Date | string
  rank?: number
  userId: string
  worldId: string
}

export type UserWorldPinUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserWorldPinUncheckedUpdateManyInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  worldId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserWorldPinListRelationFilter = {
  every?: Prisma.UserWorldPinWhereInput
  some?: Prisma.UserWorldPinWhereInput
  none?: Prisma.UserWorldPinWhereInput
}

export type UserWorldPinOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserWorldPinUserIdWorldIdCompoundUniqueInput = {
  userId: string
  worldId: string
}

export type UserWorldPinCountOrderByAggregateInput = {
  createdAt?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
}

export type UserWorldPinAvgOrderByAggregateInput = {
  rank?: Prisma.SortOrder
}

export type UserWorldPinMaxOrderByAggregateInput = {
  createdAt?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
}

export type UserWorldPinMinOrderByAggregateInput = {
  createdAt?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  worldId?: Prisma.SortOrder
}

export type UserWorldPinSumOrderByAggregateInput = {
  rank?: Prisma.SortOrder
}

export type UserWorldPinCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserWorldPinCreateWithoutUserInput, Prisma.UserWorldPinUncheckedCreateWithoutUserInput> | Prisma.UserWorldPinCreateWithoutUserInput[] | Prisma.UserWorldPinUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserWorldPinCreateOrConnectWithoutUserInput | Prisma.UserWorldPinCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserWorldPinCreateManyUserInputEnvelope
  connect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
}

export type UserWorldPinUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserWorldPinCreateWithoutUserInput, Prisma.UserWorldPinUncheckedCreateWithoutUserInput> | Prisma.UserWorldPinCreateWithoutUserInput[] | Prisma.UserWorldPinUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserWorldPinCreateOrConnectWithoutUserInput | Prisma.UserWorldPinCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserWorldPinCreateManyUserInputEnvelope
  connect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
}

export type UserWorldPinUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserWorldPinCreateWithoutUserInput, Prisma.UserWorldPinUncheckedCreateWithoutUserInput> | Prisma.UserWorldPinCreateWithoutUserInput[] | Prisma.UserWorldPinUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserWorldPinCreateOrConnectWithoutUserInput | Prisma.UserWorldPinCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserWorldPinUpsertWithWhereUniqueWithoutUserInput | Prisma.UserWorldPinUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserWorldPinCreateManyUserInputEnvelope
  set?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  disconnect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  delete?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  connect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  update?: Prisma.UserWorldPinUpdateWithWhereUniqueWithoutUserInput | Prisma.UserWorldPinUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserWorldPinUpdateManyWithWhereWithoutUserInput | Prisma.UserWorldPinUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserWorldPinScalarWhereInput | Prisma.UserWorldPinScalarWhereInput[]
}

export type UserWorldPinUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserWorldPinCreateWithoutUserInput, Prisma.UserWorldPinUncheckedCreateWithoutUserInput> | Prisma.UserWorldPinCreateWithoutUserInput[] | Prisma.UserWorldPinUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserWorldPinCreateOrConnectWithoutUserInput | Prisma.UserWorldPinCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserWorldPinUpsertWithWhereUniqueWithoutUserInput | Prisma.UserWorldPinUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserWorldPinCreateManyUserInputEnvelope
  set?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  disconnect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  delete?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  connect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  update?: Prisma.UserWorldPinUpdateWithWhereUniqueWithoutUserInput | Prisma.UserWorldPinUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserWorldPinUpdateManyWithWhereWithoutUserInput | Prisma.UserWorldPinUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserWorldPinScalarWhereInput | Prisma.UserWorldPinScalarWhereInput[]
}

export type UserWorldPinCreateNestedManyWithoutWorldInput = {
  create?: Prisma.XOR<Prisma.UserWorldPinCreateWithoutWorldInput, Prisma.UserWorldPinUncheckedCreateWithoutWorldInput> | Prisma.UserWorldPinCreateWithoutWorldInput[] | Prisma.UserWorldPinUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.UserWorldPinCreateOrConnectWithoutWorldInput | Prisma.UserWorldPinCreateOrConnectWithoutWorldInput[]
  createMany?: Prisma.UserWorldPinCreateManyWorldInputEnvelope
  connect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
}

export type UserWorldPinUncheckedCreateNestedManyWithoutWorldInput = {
  create?: Prisma.XOR<Prisma.UserWorldPinCreateWithoutWorldInput, Prisma.UserWorldPinUncheckedCreateWithoutWorldInput> | Prisma.UserWorldPinCreateWithoutWorldInput[] | Prisma.UserWorldPinUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.UserWorldPinCreateOrConnectWithoutWorldInput | Prisma.UserWorldPinCreateOrConnectWithoutWorldInput[]
  createMany?: Prisma.UserWorldPinCreateManyWorldInputEnvelope
  connect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
}

export type UserWorldPinUpdateManyWithoutWorldNestedInput = {
  create?: Prisma.XOR<Prisma.UserWorldPinCreateWithoutWorldInput, Prisma.UserWorldPinUncheckedCreateWithoutWorldInput> | Prisma.UserWorldPinCreateWithoutWorldInput[] | Prisma.UserWorldPinUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.UserWorldPinCreateOrConnectWithoutWorldInput | Prisma.UserWorldPinCreateOrConnectWithoutWorldInput[]
  upsert?: Prisma.UserWorldPinUpsertWithWhereUniqueWithoutWorldInput | Prisma.UserWorldPinUpsertWithWhereUniqueWithoutWorldInput[]
  createMany?: Prisma.UserWorldPinCreateManyWorldInputEnvelope
  set?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  disconnect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  delete?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  connect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  update?: Prisma.UserWorldPinUpdateWithWhereUniqueWithoutWorldInput | Prisma.UserWorldPinUpdateWithWhereUniqueWithoutWorldInput[]
  updateMany?: Prisma.UserWorldPinUpdateManyWithWhereWithoutWorldInput | Prisma.UserWorldPinUpdateManyWithWhereWithoutWorldInput[]
  deleteMany?: Prisma.UserWorldPinScalarWhereInput | Prisma.UserWorldPinScalarWhereInput[]
}

export type UserWorldPinUncheckedUpdateManyWithoutWorldNestedInput = {
  create?: Prisma.XOR<Prisma.UserWorldPinCreateWithoutWorldInput, Prisma.UserWorldPinUncheckedCreateWithoutWorldInput> | Prisma.UserWorldPinCreateWithoutWorldInput[] | Prisma.UserWorldPinUncheckedCreateWithoutWorldInput[]
  connectOrCreate?: Prisma.UserWorldPinCreateOrConnectWithoutWorldInput | Prisma.UserWorldPinCreateOrConnectWithoutWorldInput[]
  upsert?: Prisma.UserWorldPinUpsertWithWhereUniqueWithoutWorldInput | Prisma.UserWorldPinUpsertWithWhereUniqueWithoutWorldInput[]
  createMany?: Prisma.UserWorldPinCreateManyWorldInputEnvelope
  set?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  disconnect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  delete?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  connect?: Prisma.UserWorldPinWhereUniqueInput | Prisma.UserWorldPinWhereUniqueInput[]
  update?: Prisma.UserWorldPinUpdateWithWhereUniqueWithoutWorldInput | Prisma.UserWorldPinUpdateWithWhereUniqueWithoutWorldInput[]
  updateMany?: Prisma.UserWorldPinUpdateManyWithWhereWithoutWorldInput | Prisma.UserWorldPinUpdateManyWithWhereWithoutWorldInput[]
  deleteMany?: Prisma.UserWorldPinScalarWhereInput | Prisma.UserWorldPinScalarWhereInput[]
}

export type UserWorldPinCreateWithoutUserInput = {
  createdAt?: Date | string
  rank?: number
  world: Prisma.WorldCreateNestedOneWithoutUserPinsInput
}

export type UserWorldPinUncheckedCreateWithoutUserInput = {
  createdAt?: Date | string
  rank?: number
  worldId: string
}

export type UserWorldPinCreateOrConnectWithoutUserInput = {
  where: Prisma.UserWorldPinWhereUniqueInput
  create: Prisma.XOR<Prisma.UserWorldPinCreateWithoutUserInput, Prisma.UserWorldPinUncheckedCreateWithoutUserInput>
}

export type UserWorldPinCreateManyUserInputEnvelope = {
  data: Prisma.UserWorldPinCreateManyUserInput | Prisma.UserWorldPinCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserWorldPinUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserWorldPinWhereUniqueInput
  update: Prisma.XOR<Prisma.UserWorldPinUpdateWithoutUserInput, Prisma.UserWorldPinUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserWorldPinCreateWithoutUserInput, Prisma.UserWorldPinUncheckedCreateWithoutUserInput>
}

export type UserWorldPinUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserWorldPinWhereUniqueInput
  data: Prisma.XOR<Prisma.UserWorldPinUpdateWithoutUserInput, Prisma.UserWorldPinUncheckedUpdateWithoutUserInput>
}

export type UserWorldPinUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserWorldPinScalarWhereInput
  data: Prisma.XOR<Prisma.UserWorldPinUpdateManyMutationInput, Prisma.UserWorldPinUncheckedUpdateManyWithoutUserInput>
}

export type UserWorldPinScalarWhereInput = {
  AND?: Prisma.UserWorldPinScalarWhereInput | Prisma.UserWorldPinScalarWhereInput[]
  OR?: Prisma.UserWorldPinScalarWhereInput[]
  NOT?: Prisma.UserWorldPinScalarWhereInput | Prisma.UserWorldPinScalarWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"UserWorldPin"> | Date | string
  rank?: Prisma.IntFilter<"UserWorldPin"> | number
  userId?: Prisma.StringFilter<"UserWorldPin"> | string
  worldId?: Prisma.StringFilter<"UserWorldPin"> | string
}

export type UserWorldPinCreateWithoutWorldInput = {
  createdAt?: Date | string
  rank?: number
  user: Prisma.UserCreateNestedOneWithoutWorldPinsInput
}

export type UserWorldPinUncheckedCreateWithoutWorldInput = {
  createdAt?: Date | string
  rank?: number
  userId: string
}

export type UserWorldPinCreateOrConnectWithoutWorldInput = {
  where: Prisma.UserWorldPinWhereUniqueInput
  create: Prisma.XOR<Prisma.UserWorldPinCreateWithoutWorldInput, Prisma.UserWorldPinUncheckedCreateWithoutWorldInput>
}

export type UserWorldPinCreateManyWorldInputEnvelope = {
  data: Prisma.UserWorldPinCreateManyWorldInput | Prisma.UserWorldPinCreateManyWorldInput[]
  skipDuplicates?: boolean
}

export type UserWorldPinUpsertWithWhereUniqueWithoutWorldInput = {
  where: Prisma.UserWorldPinWhereUniqueInput
  update: Prisma.XOR<Prisma.UserWorldPinUpdateWithoutWorldInput, Prisma.UserWorldPinUncheckedUpdateWithoutWorldInput>
  create: Prisma.XOR<Prisma.UserWorldPinCreateWithoutWorldInput, Prisma.UserWorldPinUncheckedCreateWithoutWorldInput>
}

export type UserWorldPinUpdateWithWhereUniqueWithoutWorldInput = {
  where: Prisma.UserWorldPinWhereUniqueInput
  data: Prisma.XOR<Prisma.UserWorldPinUpdateWithoutWorldInput, Prisma.UserWorldPinUncheckedUpdateWithoutWorldInput>
}

export type UserWorldPinUpdateManyWithWhereWithoutWorldInput = {
  where: Prisma.UserWorldPinScalarWhereInput
  data: Prisma.XOR<Prisma.UserWorldPinUpdateManyMutationInput, Prisma.UserWorldPinUncheckedUpdateManyWithoutWorldInput>
}

export type UserWorldPinCreateManyUserInput = {
  createdAt?: Date | string
  rank?: number
  worldId: string
}

export type UserWorldPinUpdateWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  world?: Prisma.WorldUpdateOneRequiredWithoutUserPinsNestedInput
}

export type UserWorldPinUncheckedUpdateWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  worldId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserWorldPinUncheckedUpdateManyWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  worldId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserWorldPinCreateManyWorldInput = {
  createdAt?: Date | string
  rank?: number
  userId: string
}

export type UserWorldPinUpdateWithoutWorldInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutWorldPinsNestedInput
}

export type UserWorldPinUncheckedUpdateWithoutWorldInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UserWorldPinUncheckedUpdateManyWithoutWorldInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type UserWorldPinSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  createdAt?: boolean
  rank?: boolean
  userId?: boolean
  worldId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userWorldPin"]>

export type UserWorldPinSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  createdAt?: boolean
  rank?: boolean
  userId?: boolean
  worldId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userWorldPin"]>

export type UserWorldPinSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  createdAt?: boolean
  rank?: boolean
  userId?: boolean
  worldId?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userWorldPin"]>

export type UserWorldPinSelectScalar = {
  createdAt?: boolean
  rank?: boolean
  userId?: boolean
  worldId?: boolean
}

export type UserWorldPinOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"createdAt" | "rank" | "userId" | "worldId", ExtArgs["result"]["userWorldPin"]>
export type UserWorldPinInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}
export type UserWorldPinIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}
export type UserWorldPinIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  world?: boolean | Prisma.WorldDefaultArgs<ExtArgs>
}

export type $UserWorldPinPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserWorldPin"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    world: Prisma.$WorldPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    createdAt: Date
    rank: number
    userId: string
    worldId: string
  }, ExtArgs["result"]["userWorldPin"]>
  composites: {}
}

export type UserWorldPinGetPayload<S extends boolean | null | undefined | UserWorldPinDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload, S>

export type UserWorldPinCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserWorldPinFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserWorldPinCountAggregateInputType | true
  }

export interface UserWorldPinDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserWorldPin'], meta: { name: 'UserWorldPin' } }
  /**
   * Find zero or one UserWorldPin that matches the filter.
   * @param {UserWorldPinFindUniqueArgs} args - Arguments to find a UserWorldPin
   * @example
   * // Get one UserWorldPin
   * const userWorldPin = await prisma.userWorldPin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserWorldPinFindUniqueArgs>(args: Prisma.SelectSubset<T, UserWorldPinFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserWorldPinClient<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserWorldPin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserWorldPinFindUniqueOrThrowArgs} args - Arguments to find a UserWorldPin
   * @example
   * // Get one UserWorldPin
   * const userWorldPin = await prisma.userWorldPin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserWorldPinFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserWorldPinFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserWorldPinClient<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserWorldPin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserWorldPinFindFirstArgs} args - Arguments to find a UserWorldPin
   * @example
   * // Get one UserWorldPin
   * const userWorldPin = await prisma.userWorldPin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserWorldPinFindFirstArgs>(args?: Prisma.SelectSubset<T, UserWorldPinFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserWorldPinClient<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserWorldPin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserWorldPinFindFirstOrThrowArgs} args - Arguments to find a UserWorldPin
   * @example
   * // Get one UserWorldPin
   * const userWorldPin = await prisma.userWorldPin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserWorldPinFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserWorldPinFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserWorldPinClient<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserWorldPins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserWorldPinFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserWorldPins
   * const userWorldPins = await prisma.userWorldPin.findMany()
   * 
   * // Get first 10 UserWorldPins
   * const userWorldPins = await prisma.userWorldPin.findMany({ take: 10 })
   * 
   * // Only select the `createdAt`
   * const userWorldPinWithCreatedAtOnly = await prisma.userWorldPin.findMany({ select: { createdAt: true } })
   * 
   */
  findMany<T extends UserWorldPinFindManyArgs>(args?: Prisma.SelectSubset<T, UserWorldPinFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserWorldPin.
   * @param {UserWorldPinCreateArgs} args - Arguments to create a UserWorldPin.
   * @example
   * // Create one UserWorldPin
   * const UserWorldPin = await prisma.userWorldPin.create({
   *   data: {
   *     // ... data to create a UserWorldPin
   *   }
   * })
   * 
   */
  create<T extends UserWorldPinCreateArgs>(args: Prisma.SelectSubset<T, UserWorldPinCreateArgs<ExtArgs>>): Prisma.Prisma__UserWorldPinClient<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserWorldPins.
   * @param {UserWorldPinCreateManyArgs} args - Arguments to create many UserWorldPins.
   * @example
   * // Create many UserWorldPins
   * const userWorldPin = await prisma.userWorldPin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserWorldPinCreateManyArgs>(args?: Prisma.SelectSubset<T, UserWorldPinCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserWorldPins and returns the data saved in the database.
   * @param {UserWorldPinCreateManyAndReturnArgs} args - Arguments to create many UserWorldPins.
   * @example
   * // Create many UserWorldPins
   * const userWorldPin = await prisma.userWorldPin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserWorldPins and only return the `createdAt`
   * const userWorldPinWithCreatedAtOnly = await prisma.userWorldPin.createManyAndReturn({
   *   select: { createdAt: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserWorldPinCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserWorldPinCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserWorldPin.
   * @param {UserWorldPinDeleteArgs} args - Arguments to delete one UserWorldPin.
   * @example
   * // Delete one UserWorldPin
   * const UserWorldPin = await prisma.userWorldPin.delete({
   *   where: {
   *     // ... filter to delete one UserWorldPin
   *   }
   * })
   * 
   */
  delete<T extends UserWorldPinDeleteArgs>(args: Prisma.SelectSubset<T, UserWorldPinDeleteArgs<ExtArgs>>): Prisma.Prisma__UserWorldPinClient<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserWorldPin.
   * @param {UserWorldPinUpdateArgs} args - Arguments to update one UserWorldPin.
   * @example
   * // Update one UserWorldPin
   * const userWorldPin = await prisma.userWorldPin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserWorldPinUpdateArgs>(args: Prisma.SelectSubset<T, UserWorldPinUpdateArgs<ExtArgs>>): Prisma.Prisma__UserWorldPinClient<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserWorldPins.
   * @param {UserWorldPinDeleteManyArgs} args - Arguments to filter UserWorldPins to delete.
   * @example
   * // Delete a few UserWorldPins
   * const { count } = await prisma.userWorldPin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserWorldPinDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserWorldPinDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserWorldPins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserWorldPinUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserWorldPins
   * const userWorldPin = await prisma.userWorldPin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserWorldPinUpdateManyArgs>(args: Prisma.SelectSubset<T, UserWorldPinUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserWorldPins and returns the data updated in the database.
   * @param {UserWorldPinUpdateManyAndReturnArgs} args - Arguments to update many UserWorldPins.
   * @example
   * // Update many UserWorldPins
   * const userWorldPin = await prisma.userWorldPin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserWorldPins and only return the `createdAt`
   * const userWorldPinWithCreatedAtOnly = await prisma.userWorldPin.updateManyAndReturn({
   *   select: { createdAt: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserWorldPinUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserWorldPinUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserWorldPin.
   * @param {UserWorldPinUpsertArgs} args - Arguments to update or create a UserWorldPin.
   * @example
   * // Update or create a UserWorldPin
   * const userWorldPin = await prisma.userWorldPin.upsert({
   *   create: {
   *     // ... data to create a UserWorldPin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserWorldPin we want to update
   *   }
   * })
   */
  upsert<T extends UserWorldPinUpsertArgs>(args: Prisma.SelectSubset<T, UserWorldPinUpsertArgs<ExtArgs>>): Prisma.Prisma__UserWorldPinClient<runtime.Types.Result.GetResult<Prisma.$UserWorldPinPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserWorldPins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserWorldPinCountArgs} args - Arguments to filter UserWorldPins to count.
   * @example
   * // Count the number of UserWorldPins
   * const count = await prisma.userWorldPin.count({
   *   where: {
   *     // ... the filter for the UserWorldPins we want to count
   *   }
   * })
  **/
  count<T extends UserWorldPinCountArgs>(
    args?: Prisma.Subset<T, UserWorldPinCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserWorldPinCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserWorldPin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserWorldPinAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserWorldPinAggregateArgs>(args: Prisma.Subset<T, UserWorldPinAggregateArgs>): Prisma.PrismaPromise<GetUserWorldPinAggregateType<T>>

  /**
   * Group by UserWorldPin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserWorldPinGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserWorldPinGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserWorldPinGroupByArgs['orderBy'] }
      : { orderBy?: UserWorldPinGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserWorldPinGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserWorldPinGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserWorldPin model
 */
readonly fields: UserWorldPinFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserWorldPin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserWorldPinClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  world<T extends Prisma.WorldDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorldDefaultArgs<ExtArgs>>): Prisma.Prisma__WorldClient<runtime.Types.Result.GetResult<Prisma.$WorldPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserWorldPin model
 */
export interface UserWorldPinFieldRefs {
  readonly createdAt: Prisma.FieldRef<"UserWorldPin", 'DateTime'>
  readonly rank: Prisma.FieldRef<"UserWorldPin", 'Int'>
  readonly userId: Prisma.FieldRef<"UserWorldPin", 'String'>
  readonly worldId: Prisma.FieldRef<"UserWorldPin", 'String'>
}
    

// Custom InputTypes
/**
 * UserWorldPin findUnique
 */
export type UserWorldPinFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
  /**
   * Filter, which UserWorldPin to fetch.
   */
  where: Prisma.UserWorldPinWhereUniqueInput
}

/**
 * UserWorldPin findUniqueOrThrow
 */
export type UserWorldPinFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
  /**
   * Filter, which UserWorldPin to fetch.
   */
  where: Prisma.UserWorldPinWhereUniqueInput
}

/**
 * UserWorldPin findFirst
 */
export type UserWorldPinFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
  /**
   * Filter, which UserWorldPin to fetch.
   */
  where?: Prisma.UserWorldPinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserWorldPins to fetch.
   */
  orderBy?: Prisma.UserWorldPinOrderByWithRelationInput | Prisma.UserWorldPinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserWorldPins.
   */
  cursor?: Prisma.UserWorldPinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserWorldPins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserWorldPins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserWorldPins.
   */
  distinct?: Prisma.UserWorldPinScalarFieldEnum | Prisma.UserWorldPinScalarFieldEnum[]
}

/**
 * UserWorldPin findFirstOrThrow
 */
export type UserWorldPinFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
  /**
   * Filter, which UserWorldPin to fetch.
   */
  where?: Prisma.UserWorldPinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserWorldPins to fetch.
   */
  orderBy?: Prisma.UserWorldPinOrderByWithRelationInput | Prisma.UserWorldPinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserWorldPins.
   */
  cursor?: Prisma.UserWorldPinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserWorldPins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserWorldPins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserWorldPins.
   */
  distinct?: Prisma.UserWorldPinScalarFieldEnum | Prisma.UserWorldPinScalarFieldEnum[]
}

/**
 * UserWorldPin findMany
 */
export type UserWorldPinFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
  /**
   * Filter, which UserWorldPins to fetch.
   */
  where?: Prisma.UserWorldPinWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserWorldPins to fetch.
   */
  orderBy?: Prisma.UserWorldPinOrderByWithRelationInput | Prisma.UserWorldPinOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserWorldPins.
   */
  cursor?: Prisma.UserWorldPinWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserWorldPins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserWorldPins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserWorldPins.
   */
  distinct?: Prisma.UserWorldPinScalarFieldEnum | Prisma.UserWorldPinScalarFieldEnum[]
}

/**
 * UserWorldPin create
 */
export type UserWorldPinCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
  /**
   * The data needed to create a UserWorldPin.
   */
  data: Prisma.XOR<Prisma.UserWorldPinCreateInput, Prisma.UserWorldPinUncheckedCreateInput>
}

/**
 * UserWorldPin createMany
 */
export type UserWorldPinCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserWorldPins.
   */
  data: Prisma.UserWorldPinCreateManyInput | Prisma.UserWorldPinCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserWorldPin createManyAndReturn
 */
export type UserWorldPinCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * The data used to create many UserWorldPins.
   */
  data: Prisma.UserWorldPinCreateManyInput | Prisma.UserWorldPinCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserWorldPin update
 */
export type UserWorldPinUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
  /**
   * The data needed to update a UserWorldPin.
   */
  data: Prisma.XOR<Prisma.UserWorldPinUpdateInput, Prisma.UserWorldPinUncheckedUpdateInput>
  /**
   * Choose, which UserWorldPin to update.
   */
  where: Prisma.UserWorldPinWhereUniqueInput
}

/**
 * UserWorldPin updateMany
 */
export type UserWorldPinUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserWorldPins.
   */
  data: Prisma.XOR<Prisma.UserWorldPinUpdateManyMutationInput, Prisma.UserWorldPinUncheckedUpdateManyInput>
  /**
   * Filter which UserWorldPins to update
   */
  where?: Prisma.UserWorldPinWhereInput
  /**
   * Limit how many UserWorldPins to update.
   */
  limit?: number
}

/**
 * UserWorldPin updateManyAndReturn
 */
export type UserWorldPinUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * The data used to update UserWorldPins.
   */
  data: Prisma.XOR<Prisma.UserWorldPinUpdateManyMutationInput, Prisma.UserWorldPinUncheckedUpdateManyInput>
  /**
   * Filter which UserWorldPins to update
   */
  where?: Prisma.UserWorldPinWhereInput
  /**
   * Limit how many UserWorldPins to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserWorldPin upsert
 */
export type UserWorldPinUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
  /**
   * The filter to search for the UserWorldPin to update in case it exists.
   */
  where: Prisma.UserWorldPinWhereUniqueInput
  /**
   * In case the UserWorldPin found by the `where` argument doesn't exist, create a new UserWorldPin with this data.
   */
  create: Prisma.XOR<Prisma.UserWorldPinCreateInput, Prisma.UserWorldPinUncheckedCreateInput>
  /**
   * In case the UserWorldPin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserWorldPinUpdateInput, Prisma.UserWorldPinUncheckedUpdateInput>
}

/**
 * UserWorldPin delete
 */
export type UserWorldPinDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
  /**
   * Filter which UserWorldPin to delete.
   */
  where: Prisma.UserWorldPinWhereUniqueInput
}

/**
 * UserWorldPin deleteMany
 */
export type UserWorldPinDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserWorldPins to delete
   */
  where?: Prisma.UserWorldPinWhereInput
  /**
   * Limit how many UserWorldPins to delete.
   */
  limit?: number
}

/**
 * UserWorldPin without action
 */
export type UserWorldPinDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserWorldPin
   */
  select?: Prisma.UserWorldPinSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserWorldPin
   */
  omit?: Prisma.UserWorldPinOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserWorldPinInclude<ExtArgs> | null
}
